### ISSUE TITLE
An unexpected error occured: Error: Failed to parse string

### ISSUE THREAD

**Issue by karltaylor** [Connected-Information-systems/diff-test-coverage#4]
Trying to get it to work with lcov and jest tests. Here's my command and result:

```sh
git diff develop...feature/update-mentions | diff-test-coverage -c coverage/clover.xml -t lcov --
An unexpected error occurred: Error: Failed to parse string
    at maybeWrapAsError (/Users/karl/.nvm/versions/node/v10.16.3/lib/node_modules/@connectis/diff-test-coverage/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/karl/.nvm/versions/node/v10.16.3/lib/node_modules/@connectis/diff-test-coverage/node_modules/bluebird/js/release/nodeback.js:38:50
    at walkFile (/Users/karl/.nvm/versions/node/v10.16.3/lib/node_modules/@connectis/diff-test-coverage/node_modules/lcov-parse/lib/index.js:108:9)
    at /Users/karl/.nvm/versions/node/v10.16.3/lib/node_modules/@connectis/diff-test-coverage/node_modules/lcov-parse/lib/index.js:118:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by marklagendijk** [comment]
Looks like you're mixing things up. You're trying to parse a `clover` formatted file using the `lcov` type.
Also, jest supports multiple coverage report formats, so if there would be an issue with one, you could try the other ones.
